export const Routes = {
  LOADING: 'loading',
  LOGIN: 'login',
  SignUp: 'signUp',
  CustomHeader: 'customHeader',
  WORKSPACE: 'workspace',
  CREATEWORKSPACE: 'create workspace',
  EDITWORKSPACE: 'edit workspace',
  INVITEMEMBERS: 'invite members',
  CREATEINVITEUSER: 'create invite user',
  HOME: 'home',
  DASHBOARD: 'dashboard',
  DRAWER: 'drawer',
  PRODUCTS: 'products',
  ORDERS: 'orders',
  ORDERSLIST: 'orders list',
  ORDERTIMELINE: 'order timeline',
  ORDERACTIVITY: 'order activity',
  CREATEORDERS: 'create order',
  EDITORDERS: 'edit order',
  SHOWORDER: 'show order',
  SOCIALMEDIA: 'socialmedia',
  DESIGNS: 'designs',
  INBOX: 'inbox',
  SETTINGS: 'settings',
  SHIPPERS: 'shippers',
  CREATESHIPPER: 'create shipper',
  BOTTOMTAB: 'bottom tab',
  EDITSCREEN: 'imageeditscreen',
  IMAGEMULTIPLE: 'imageeditmultiple',
  TAGS: 'tags',
  IGPOSTSSCREEN: 'ig posts screen',
  PRODUCTSHOW: 'product show',
};
export const HIDE_HEADER = {headerShown: false};
