import uuid from 'react-native-uuid';

export const initialValues = {
  workspace_id: '',
  shipperType: null,
  contactNo: '',
  name: '',
  email: '',
  address: '',
  pin_location: '',
  new_customer_city: null,
  city_id: '',
  remarks: '',
  shipper_type: '',
  weight: '',
  service_type: null,
  sale_person_id: null,
  published: {
    id: 'yes',
    name: 'Yes',
  },
  product_details: null,
  pieces: '',
  other_details: null,
  origin_id: null,
  order_query_id: null,
  insurance_value: null,
  fragile: null,
  discount_percentage: 0,
  country_id: null,
  booking_person: null,
  cod_amount: 0,
  product_type: null,
  delivery_cost: 0,
  city_name: '',
  discount_amount: 0,
  addProduct: [addProduct],
  courier_details: courierDetails,
};
const addProduct = {
  index: uuid.v4(),
  No: '',
  name: '',
  product_id: null,
  product_variant_id: null,
  warehouse_product_id: null,
  quantity: 0,
  max_quantity: 0,
  price: 0,
  discount: 0,
  isPercent: true,
  total_amount: 0,
};

const courierDetails = {
  fragile: null,
  service_type: null,
  city_id: null,
  shipping_mode: null,
  payment_mode: null,
  item_product_type: null,
  service_type_id: null,
  item_insurance: null,
  information_display: null,
};
